### PR TITLE
Fixing Miscellaneous Structure and Policy Issues

### LINKED ISSUE #140: Control access to policy and membership recording functions in Fabric Interop CC
Currently, any network client can create a new access control or verification policy, or overwrite an existing one. We need to add access control checks and enforcement mechanisms so only "privileged" users are allowed to perform these tasks. The same consideration applied to recording foreign networks' membership certificates.

### PR DESCRIPTION
**Pull request by VRamakrishna**
This PR fixes #140 , #288 , #297 .

### CODE REVIEW

File: tests/network-setups/fabric/dev/scripts/deployCC.sh [hunk 1]
```diff
@@ -25,9 +25,13 @@ PROFILE="${14}"
 CC_SRC_LANGUAGE=`echo "$CC_SRC_LANGUAGE" | tr [:upper:] [:lower:]`
 CC_CHAIN_CODE=`echo "$CC_CHAIN_CODE" | tr [:upper:] [:lower:]`
 
-CC_END_POLICY=""
+CC_END_POLICY="--signature-policy AND('Org1MSP.member')"
 if [ "$PROFILE" = "2-nodes" ]; then
-	CC_END_POLICY="--signature-policy AND('Org1MSP.member','Org2MSP.member')"
+    if [ "$CC_CHAIN_CODE" = "interop" ]; then
+		CC_END_POLICY="--signature-policy OR('Org1MSP.member','Org2MSP.member')"
+	else
```
Comment (sanvenDev) [inline tests/network-setups/fabric/dev/scripts/deployCC.sh:32]: Indentation issue here

**Comment by sanvenDev** [comment]
Update the version for InteropCC and fabric-node-sdk.

File: tests/network-setups/fabric/dev/scripts/deployCC.sh (hunk 1 above)
Comment (VRamakrishna) [reply tests/network-setups/fabric/dev/scripts/deployCC.sh:32]: Fixed.

**Review by sanvenDev — APPROVED** [review]
